export enum BarcodeFormat {
  EAN13 = 'EAN13',
  CODE128 = 'CODE128',
  CODE39 = 'CODE39',
  UPC = 'UPC',
  ITF14 = 'ITF14',
  MSI = 'MSI'
}

export interface GeneratedBarcode {
  id: string;
  code: string;
  format: BarcodeFormat;
  description: string; // Generated by AI (e.g., "Soda Can 330ml")
  timestamp: number;
}

export interface GenerationResponse {
  code: string;
  description: string;
}
